/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclel_IT13044664;

import java.awt.Toolkit;
import java.sql.ResultSet;
import mysql_conn.Mysqlconn;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;




/**
 *
 * @author Homepc
 */
public class update_vehicle extends javax.swing.JFrame {

    /**
     * Creates new form update_vehicle
     */
    
    String id=null;
    String vehiclno;
    int model;
    String vehicletype;
    String query;
    String in_ex_date,in_date;
    
    public update_vehicle() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Design1.png")));
        loadvehicletable();
        //jButton1.setEnabled(false);
        //table();
        
    }
    
    
        private void loadvehicletable() {
        try{
       Mysqlconn mysql=new Mysqlconn();
       ResultSet rs=mysql.getDataa("select vehicle_No,ve_Type,ve_Modle,ve_insurance_date,ve_insurance_ex_date from vehicle");
       DefaultTableModel df=(DefaultTableModel)jTable2.getModel();
       df.setRowCount(0);
       
       while(rs.next()){
        Vector v=new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                
                df.addRow(v);
       }
            } catch(Exception e){
        }
    }
    private void filltheTextfields() {
            try{
                jTextField3.setText(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
                jTextField4.setText(jTable2.getValueAt(jTable2.getSelectedRow(),1).toString());
                jTextField2.setText(jTable2.getValueAt(jTable2.getSelectedRow(),2).toString());
                jTextField5.setText(jTable2.getValueAt(jTable2.getSelectedRow(),3).toString());
                jTextField1.setText(jTable2.getValueAt(jTable2.getSelectedRow(),4).toString());
                       
            }
            catch(Exception e){}
    }
  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        removevehicle = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Vehicle");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Vehicle No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 37, 84, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Vehicle Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 43, -1, 25));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Vehicle Model ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 86, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Insurance Date  ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 95, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Insurance Expected Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 134, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 128, 115, 31));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 80, 115, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 32, 115, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 41, 108, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 89, 108, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0007_Tick.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 186, -1, -1));

        removevehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0005_Delete.png"))); // NOI18N
        removevehicle.setText("Remove");
        removevehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removevehicleActionPerformed(evt);
            }
        });
        getContentPane().add(removevehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 186, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0050_Clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 186, -1, -1));

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vehicle No", "Vehicle Type", "Vehicle Model ", "Insurance Date  ", "Insurance Exp Date"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jTable2.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 241, 757, 242));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Designer2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void removevehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removevehicleActionPerformed
        // TODO add your handling code here:
        vehiclno = jTextField3.getText();
        String removeQuery = "delete from vehicle where vehicle_No='"+vehiclno+"';";
        String vmremoveQuery = "delete from vehiclemaintains where vehiclenumber='"+vehiclno+"';";
        String sqlquery="update drivers set vehicle_number='' where vehicle_number='"+vehiclno+"';";
        new Mysqlconn().update(sqlquery);
        new Mysqlconn().update(vmremoveQuery);
        new Mysqlconn().update(removeQuery);
        
        JOptionPane.showMessageDialog(null,"delete Successfull");
        loadvehicletable();
        jButton3ActionPerformed(evt);
        
    }//GEN-LAST:event_removevehicleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText(" ");
        jTextField2.setText(" ");
        jTextField1.setText(" ");
        jTextField4.setText(" ");
        jTextField5.setText(" ");
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        id=null;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Manuvehicle().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        id=jTable2.getValueAt(jTable2.getSelectedRow(),0).toString();
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        System.out.println(id);
        filltheTextfields();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(id==null)
        {
            JOptionPane.showMessageDialog(null,"Select The Details ", "Empty ",0);
        }
        else{
            vehiclno = jTextField3.getText();
        // model=Integer.parseInt(jTextField2.getText());
        vehicletype =jTextField4.getText();
        in_date=jTextField5.getText();
        in_ex_date=jTextField1.getText();

        try {
            model = Integer.parseInt(jTextField2.getText());
        } catch (NumberFormatException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, " Enter valid Number for vehicle model. ", " Invalid Inputs", 2);
        }

        if(vehiclno.length()==0||vehicletype.length()==0||in_date.length()==0||in_ex_date.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Enter the text Fileds ");
       System.out.println("Enter the text Fileds");
        }    
        else{
                  String string =jTextField5.getText();
                    String[] parts = string.split("-");
                    String part1 = parts[0];
                    String part2 = parts[1];
                    String part3 = parts[2]; 


                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DATE);
                    month=month+1;
                    String calmon=0+Integer.toString(month);
                    String calday=Integer.toString(day);

                    int ye=Integer.parseInt(part1);
                      
                                String calyer=Integer.toString(year)+calmon;
                                int chmonth=Integer.parseInt(calyer);
                                String uschmonth=part1+part2;
                                System.out.println(uschmonth);
                                System.out.println(calyer);
                                int usdate=Integer.parseInt(uschmonth);
                                if(usdate<=chmonth)
                                {
                                    String string1 =jTextField1.getText();
                                    String[] parts1 = string1.split("-");
                                    String part10 = parts1[0];
                                    int us_in_ex_date=Integer.parseInt(part10);
                                    if(us_in_ex_date>year)
                                    {
                                        
                                        
                                        Mysqlconn sql=new Mysqlconn();
                                        query="update vehicle set ve_Type='"+vehicletype+"',ve_Modle="+model+",ve_insurance_date='"+in_date+"',ve_insurance_ex_date='"+in_ex_date+"'where vehicle_No='"+vehiclno+"';";
                                        sql.update(query);
                                        JOptionPane.showMessageDialog(null,"Vehicle Update is Successfull ");
                                        loadvehicletable();
                                        jButton3ActionPerformed(evt);
                                    }
                                    else{
                                        JOptionPane.showMessageDialog(null, " Invalid Insurance Expected Date Is Entered. ", " Invalid Inputs", 2);
                                    }
                                    
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, " Invalid Insurance Date Is Entered. ", " Invalid Inputs", 2);
                                return;
                                }
                                
                                
                         
                            }
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_vehicle().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton removevehicle;
    // End of variables declaration//GEN-END:variables
}


