/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclel_IT13044664;

import gui.DatePicker;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Vector;
import mysql_conn.Mysqlconn;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishanth
 */
public class Vehicle_maintenance extends javax.swing.JFrame {

    /**
     * Creates new form Vehicle_maintenance
     */
    
    String ve_no;
    String Date,Des;
    int amount;
    String venum,id;
    public Vehicle_maintenance() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Design1.png")));
        fillvehiclenumber();
        buttondiable();
        loadTable();
    }

    
    private void fillvehiclenumber() {
        Mysqlconn dao = new Mysqlconn();
        ArrayList CatList = dao.getvehiclenumber();

        Iterator i = CatList.iterator();

        while (i.hasNext()) {
            jComboBox1.addItem(i.next());
        }
        

       

       
    }
    public void buttondiable(){
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }
    
    private void loadTable() {
        try{
       Mysqlconn mysql=new Mysqlconn();
       ResultSet rs=mysql.getDataa("select Amount,Description,Date,vehiclenumber,ve_maintains_ID from vehiclemaintains");
       DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
       df.setRowCount(0);
       
       while(rs.next()){
        Vector v=new Vector();
                v.add(rs.getString(5));
                v.add(rs.getString(4));
                v.add(rs.getString(3));
                v.add(rs.getString(2));
                v.add(rs.getString(1));
                
                
                df.addRow(v);
       }
            } catch(Exception e){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle Maintenance Cost");
        setPreferredSize(new java.awt.Dimension(1000, 610));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID","vehicle Numbre", "Date", "Description", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 900, 200));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Vehicle Maintenance Cost");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 280, 49));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Vehicle No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 74, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {""}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 102, 25));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0038_Calender.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 102, 32));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 199, 72));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Description");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 116, 34));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Amount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0007_Tick.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 110, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0007_Tick.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 111, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0005_Delete.png"))); // NOI18N
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 120, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_0050_Clear.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/824_p.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker(this);
       jTextField1.setText(datePicker.setPickedDate());
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Manuvehicle().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ve_no=jComboBox1.getSelectedItem().toString();
        Date=jTextField1.getText();
        Des=jTextArea1.getText();
       // 
        
        if(ve_no.length()==0||Date.length()==0||Des.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Fill in the details.");
        }
        else{
            try{
               amount=Integer.parseInt(jTextField2.getText()); 
            }
            catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Enter the valide number for Amount",  "NumberFormatException", 3);
            return;
            }
            if(Des.length()<=50)
            {
                boolean date=datacheach();
                                if(date)
                                {
                                    
                                
                
                      ArrayList CatList =new Mysqlconn().getid();
                      Iterator i = CatList.iterator();
                      String id=(String) i.next();
                      if(id == null)
                      {
                String SqlQrery="insert into vehiclemaintains values('vm-100',"+amount+",'"+Des+"','"+Date+"','"+ve_no+"');";
                Mysqlconn sql=new Mysqlconn();
                sql.addvehicle(SqlQrery);
                JOptionPane.showMessageDialog(null,"Added to system ");
                jButton4ActionPerformed(evt);
                loadTable();
                      }
                      
                      else{
      System.out.println(id);
                    String string =id;
                    String[] parts = string.split("-");
                    String part2 = parts[1]; 
                    int vmid=Integer.parseInt(part2);
                    vmid=vmid+1;
                    String con=Integer.toString(vmid);
                    String VHID="vm-"+con;
                String SqlQrery="insert into vehiclemaintains values('"+VHID+"',"+amount+",'"+Des+"','"+Date+"','"+ve_no+"');";
                Mysqlconn sql=new Mysqlconn();
                sql.addvehicle(SqlQrery);
                JOptionPane.showMessageDialog(null,"Added to system ");
                jButton4ActionPerformed(evt);
                loadTable();
                
                      }
                //System.out.print(ve_no);
            
                                }
                                else
                                {
                                     JOptionPane.showMessageDialog(null, " Invalid Date Is Entered. ", " Invalid Inputs", 2);
                                }
                                }
            else{
                JOptionPane.showMessageDialog(null, "Description Length is More Then 50 ",  "Description Length", 3);
            return;
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextArea1.setText("");
        jTextField2.setText("");
        jComboBox1.setSelectedItem("");
        buttondiable();
        jButton1.setEnabled(true);
        jTextField1.setEditable(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        venum="";
        id=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
        venum=jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
       System.out.print(venum);
        filltheTextfields();
        jButton2.setEnabled(true);
        jButton1.setEnabled(false);
        jButton3.setEnabled(true);
        jTextField1.setEditable(false);
       
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ve_no=jComboBox1.getSelectedItem().toString();
        Date=jTextField1.getText();
        Des=jTextArea1.getText();
 
        if(ve_no.length()==0||Date.length()==0||Des.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Fill in the details.");
        }
        else{
            try{
               amount=Integer.parseInt(jTextField2.getText()); 
            }
            catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Enter the valide number for Amount",  "NumberFormatException", 3);
            return;
            }
            if(Des.length()<=50)
            {
                boolean date=datacheach();
                if(date)
                {
                String SqlQrery="update vehiclemaintains set Date='"+Date+"',Amount='"+amount+"',Description='"+Des+"' where ve_Maintains_ID='"+id+"'";
                Mysqlconn sql=new Mysqlconn();
                sql.update(SqlQrery);
                JOptionPane.showMessageDialog(null,"Update SuccessfullS");
                jButton4ActionPerformed(evt);
                loadTable();
                }
                else{
                     JOptionPane.showMessageDialog(null, " Invalid Date Is Entered. ", " Invalid Inputs", 0);
                }
               
                
                //System.out.print(ve_no);
            }
            else{
                JOptionPane.showMessageDialog(null, "Description Length is More Then 50 ",  "Description Length", 3);
            return;
            }
        }
    
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String removeQuery = "delete from vehiclemaintains where ve_Maintains_ID='"+id+"';";
        
        new Mysqlconn().update(removeQuery);
        JOptionPane.showMessageDialog(null,"delete Successfull");
        loadTable();
        jButton4ActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed
private void filltheTextfields() {
            try{
                jComboBox1.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
                jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
                jTextArea1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
                jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
                     
            }
            catch(Exception e){}
    }

public boolean datacheach(){
                boolean result;
                String string1 =jTextField1.getText();
                    String[] parts1 = string1.split("-");
                    String part11 = parts1[0];
                    String part22 = parts1[1];
                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    month=month+1;
                    String calmon=0+Integer.toString(month);
                    String calyer=Integer.toString(year)+calmon;
                                int chmonth=Integer.parseInt(calyer);
                                String uschmonth=part11+part22;
                                int usdate=Integer.parseInt(uschmonth);
                                if(usdate<=chmonth)
                                {
                                   result=true; 
                                }
                                else{
                                    result=false;
                                }
                                return result;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_maintenance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}


